### ISSUE TITLE
Issue when start project

### ISSUE THREAD

**Issue by PhanHaHus** [josephspurrier/gowebapi#1]
Hey bros, when I pull code and start file gowebapi.go , it have this error, what should I do, im using go 1.8, thanks you
gowebapi.go:9:2: cannot find package "app/controller" in any of:
        C:\Go\src\app\controller (from $GOROOT)
        C:\Go\bin\src\app\controller (from $GOPATH)
gowebapi.go:10:2: cannot find package "app/route" in any of:
        C:\Go\src\app\route (from $GOROOT)
        C:\Go\bin\src\app\route (from $GOPATH)
gowebapi.go:11:2: cannot find package "app/shared/database" in any of:
        C:\Go\src\app\shared\database (from $GOROOT)

**Comment by josephspurrier** [comment]
From first glance, create a folder called gowebapi in src and then move all the code in there.

To download the code, did you do a: go get github.com/josephspurrier/gowebapi?

**Comment by PhanHaHus** [comment]
Yes, I have done go get. But it still show error like before. I think this is good structure and easier for maintain, do you have new structure for go API in 2017 ?

**Comment by josephspurrier** [comment]
Make sure your workspace looks like this: /somepath/workspace/src/github.com/josephspurrier/gowebapi/gowebapi.go

And your GOPATH is set to this: /somepath/workspace

I don't have a new version of the API, but the latest project is: https://github.com/blue-jay/blueprint. It follows some better practices.

**Comment by PhanHaHus** [comment]
Yeah, but I wanna separately server API and web client to two folder. So I follow two repositories of you.hi

**Comment by josephspurrier** [comment]
I don't have a structure for both API and web UI, but you can look at my clean architecture repository. https://github.com/josephspurrier/gocleanarchitecture

You can have multiple applications under the cmd folder that share things at the root of the project.
